name: Mirror Main Branch to Personal Repo

on:
  push:
    branches:
      - dev

jobs:
  mirror-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Push only main branch to Mirror Repo
        run: |
          # Клонируем репозиторий-зеркало в отдельную папку
          git clone "https://x-access-token:${{ secrets.PAT_FOR_MIRROR }}@github.com/NikitaSemenukha/mirror-front.git" mirror-repo

          # Копируем все файлы из исходного репозитория (кроме .git) в папку с зеркалом
          rsync -av --delete --exclude '.git/' ./ mirror-repo/

          # Заходим в папку зеркала и коммитим изменения
          cd mirror-repo
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          # Если изменений нет, команда git diff вернет код 1, поэтому `|| exit 0`
          if ! git diff --quiet; then
            git add .
            git commit -m "Sync from source repository [${{ github.sha }}]"
            git push
          else
            echo "No changes to sync."
          fi
